---
# Debian tasks file for ansible-role-linux-updates

- name: "Install needrestart package, if not already installed"
  ansible.builtin.apt:
    name: "needrestart"
    state: present

- name: "Modify needrestart.conf file"
  ansible.builtin.lineinfile:
    path: /etc/needrestart/needrestart.conf
    regexp: '^#.nrconf\{restart\}'
    line: "$nrconf{restart} = 'a';"
    state: present

- name: "Collect list of packages to update"
  ansible.builtin.shell:
    cmd: apt list --upgradable
  register: output

- name: "Set upgradable Fact"
  ansible.builtin.set_fact:
    updates: "{{ output.stdout }}"
  when:
    - output is defined
    - output.changed

- name: "Install latest updates"
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes

- name: "Deploy kernel_check.sh script"
  ansible.builtin.template:
    src: "kernel_check_debian.j2"
    dest: /usr/local/bin/kernel_check.sh
    owner: root
    group: root
    mode: '0770'

- name: "Check if reboot is required, after patching kernel"
  ansible.builtin.command:
    cmd: /usr/local/bin/kernel_check.sh
  register: reboot

- name: "Reboot host, if kernel update installed"
  ansible.builtin.reboot:
  when:
    - reboot.stdout.find("reboot") != -1

- name: "Email notification of installed packages"
  mail:
    host: "{{ smtp_host }}"
    port: "{{ smtp_port }}"
    to: "{{ recipient }}"
    from: "{{ sender }}"
    subject: "Patching Report: {{ inventory_hostname }} has been successfully updated"
    body: "{{ updates }}"
    secure: never
  delegate_to: localhost
  when:
    - updates is defined
    - updates is string

- name: "Remove dependencies that are no longer required"
  ansible.builtin.apt:
    autoremove: yes
  ignore_errors: yes

- name: "Clean Package Cache"
  ansible.builtin.shell:
    cmd: apt-get -y clean all