---
# Kernel tasks file for ansible-role-linux-updates

- name: "Test if package_cleanup boolean variable is set correctly"
  ansible.builtin.assert:
    that:
      - package_cleanup is defined
      - package_cleanup is boolean
    quiet: yes
  when:
    - ansible_facts['distribution_major_version'] <= '7'

- name: "Install yum-utils package, if not already installed (RHEL7)"
  ansible.builtin.yum:
    name: "yum-utils"
    state: present
  when:
    - not package_cleanup | bool
    - ansible_facts['distribution_major_version'] <= '7'

## https://access.redhat.com/solutions/1227 ##
- name: "Collect number of installed kernels"
  ansible.builtin.shell:
    cmd: rpm -qa kernel | wc -l
  register: kernels

- name: "Remove old kernels (yum-utils)"
  ansible.builtin.shell:
    cmd: package-cleanup -y --oldkernels --count=2
  ignore_errors: yes
  when:
    - kernels.stdout | int > 2
    - ansible_facts['distribution_major_version'] <= '7'

- name: "Remove old kernels (dnf)"
  ansible.builtin.shell:
    cmd: dnf -y remove --oldinstallonly --setopt installonly_limit=2 kernel
  ignore_errors: yes
  when:
    - kernels.stdout | int > 2
    - ansible_facts['distribution_major_version'] >= '8'
