---
# Lookup tasks file for ansible-role-linux-updates

- name: "Check for yum-utils package"
  ansible.builtin.shell:
    cmd: command -v package-cleanup
  register: result
  ignore_errors: true
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - ansible_facts['distribution_major_version'] <= '7'

- name: "Set Facts for package_cleanup variable, when installed"
  ansible.builtin.set_fact:
    package_cleanup: true
  when:
    - not result.failed | bool or ansible_facts['distribution_major_version'] >= '8'

- name: "Set Facts for package_cleanup variable, when not installed"
  ansible.builtin.set_fact:
    package_cleanup: false
  when:
    - result.failed | bool
