---
# tasks file for ansible-role-linux-updates

- ansible.builtin.include_tasks: assert.yaml

- ansible.builtin.include_tasks: "{{ ansible_facts['os_family'] }}.yaml"

- ansible.builtin.include_tasks: notification.yaml

- ansible.builtin.include_tasks: kernel.yaml
  when:
    - kernel_cleanup | bool
    - ansible_facts['os_family'] == 'RedHat'