---
# Notification tasks file for ansible-role-linux-updates

- name: "Email notification of installed packages"
  mail:
    host: "{{ smtp_host }}"
    port: "{{ smtp_port }}"
    to: "{{ recipient }}"
    from: "{{ sender }}"
    subject: "Patching Report: {{ inventory_hostname }} has been successfully updated"
    body: "{{ updates }}"
    secure: never
  delegate_to: localhost
  when:
    - updates is defined
    - updates is string